import { Inter } from "next/font/google";
import "./globals.css";
import "@contentstack/live-preview-utils/dist/main.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Contentstack Dev Starter",
  // description: "Generated by create next app",
  icons: [{rel: 'icon', url: '/favicon.ico'}]
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
